bids-apps/giga_connectome

.git_archival.txt
.github/workflows/test.yml
.gitignore
giga_connectome/outputs.py
giga_connectome/tests/test_cli.py
giga_connectome/tests/test_metadata.py
giga_connectome/tests/test_utils.py
giga_connectome/utils.py
giga_connectome/workflow.py
pyproject.toml

TEST tests and ci

---

README.md
giga_connectome/outputs.py
giga_connectome/run.py
giga_connectome/tests/test_cli.py
giga_connectome/workflow.py

- expose smoothing and standardisation
- add flag to expose version

EHN expose some preprocessing options

---

giga_connectome/__init__.py
giga_connectome/atlas.py
giga_connectome/denoise.py
giga_connectome/mask.py
giga_connectome/postprocess.py
giga_connectome/run.py
giga_connectome/tests/test_atlas.py
giga_connectome/tests/test_utils.py
giga_connectome/utils.py
giga_connectome/workflow.py

- Add BIDS filter that follows the same design as fMRIPrep
- also a lot of refactoring
- Make sure detrend only happens when cosine regressors are not present

EHN BIDS filter

---

giga_connectome/data/test_data/bids_filter.json
giga_connectome/postprocess.py
giga_connectome/run.py
giga_connectome/tests/test_cli.py
giga_connectome/utils.py
giga_connectome/workflow.py

Closes #22 
- instead of per scan.
- improve tests: add bids filter
- typing for `utils.py`

EHN participant level output per subject

---

.github/workflows/test.yml

Skip docker build if full test not requested

---

.github/dependabot.yml
.github/workflows/validate_cff.yml
CITATION.cff

- also add a dependabot to make sure that all github actions are updated monthly

[MAINT] add citation.cff file and validation workflow

---

.github/workflows/update_precommit_hooks.yml

closes none
- add GHA workflow to update pre-commit hooks every week

[MAINT] add workflow to update precommit hooks

---

.github/workflows/test.yml
pyproject.toml

[MAINT] run test suite with python 3.12

---

.github/workflows/run_precommit.yml
CITATION.cff

[MAINT] run pre-commit in CI to check style

---

pyproject.toml
requirements.txt

[MAINT] bump nilearn version to 0.10.2

---

.gitignore
giga_connectome/atlas.py
giga_connectome/logger.py
giga_connectome/mask.py
giga_connectome/postprocess.py
giga_connectome/run.py
giga_connectome/tests/test_mask.py
giga_connectome/utils.py
giga_connectome/workflow.py
pyproject.toml
tools/download_templates.py

- closes #62 
---
- add logger
- set verbosity level from CLI
- remove print statement and passing verbosity level as argument

[ENH] use logger instead of print statements

---

README.md

- mentioned in https://github.com/SIMEXP/giga_connectome/issues/44#issue-1895346629
---
- add badge for black
- add badge for linting
- add badge for test

[DOC] add badges to readme

---

giga_connectome/data/methods/template.jinja
giga_connectome/methods.py
giga_connectome/postprocess.py
giga_connectome/run.py
giga_connectome/tests/test_cli.py
giga_connectome/tests/test_methods.py
giga_connectome/workflow.py

Closes #79.
- remove group as an option from CLI
- show a warning when anything that's not 'participant', and let the process run anyway
- update the methods template accordingly

Remove all group level related process from the workflow

---

docs/source/changes.md
docs/source/installation.md
docs/source/usage.md

Closes #106 
- Added detailed examples for customised atlas and denoising strategy when using a container
- update singularity -> apptainer

Improve documentation on customised atlas and denoising strategy

---

paper/paper.md

Update of my affiliation and ORCID in paper/paper.md

Add Quentin's details

---

README.md

[MAINT] update codecov badge

---

.github/workflows/update_precommit_hooks.yml
CITATION.cff
README.md
docs/source/changes.md
docs/source/contributing.md
docs/source/installation.md
docs/source/usage.md
giga_connectome/utils.py
pyproject.toml

- closes #129 
- also updates to the new repo URL

[DOC] add docker badge and update docs and links

---

.github/workflows/docker.yml
Dockerfile
README.md
docs/source/changes.md
giga_connectome/atlas.py
giga_connectome/data/atlas/HarvardOxfordCortical.json
giga_connectome/data/atlas/HarvardOxfordCorticalSymmetricSplit.json
giga_connectome/data/atlas/HarvardOxfordSubcortical.json
giga_connectome/run.py
giga_connectome/tests/test_atlas.py
tools/download_templates.py

Closes #117.
- Add harvard oxford atlas (cortical, cortical split, subcortical) threshold 25% and 50%
- grab preset atlas from the data directory rather than hard coding.
- Docker image test for all default atlases

ENH harvard oxford atlas

---

giga_connectome/mask.py
giga_connectome/tests/test_cli.py

FIX reuse pregenerated subject segmentation or masks

---

.all-contributorsrc
README.md
docs/source/contributing.md

Add all contributor bots

---

LICENSE
README.md
docs/source/changes.md
docs/source/installation.md
docs/source/usage.md
giga_connectome/run.py

Closes #212. 
- Major content change: Use actual runnable code and test data for advance usage.
- Various small updates:
- Update licence
- README file: link to contribution docs, nilearn citation
- Usage: fix CLI help message rendering, broken link, update parameters in examples to avoid the deprecation warning

JOSS - Improvement on advance usages examples

---

giga_connectome/denoise.py
giga_connectome/tests/test_cli.py
giga_connectome/tests/test_denoise.py
giga_connectome/tests/test_utils.py
giga_connectome/utils.py
giga_connectome/workflow.py

Close #211.
- Make sure the correct files are indexed through BIDS filters
- Ensure the correct files can go through the de-noising workflow and generate correct meta data

FIX ICA-AROMA implementation

---

docs/source/contributing.md
docs/source/outputs.md
docs/source/usage.md
paper/paper.md

Minor edits on docs

---

paper/paper.bib
paper/paper.md

Here some minor fixes/changes for the JOSS paper and its bibliography. Please merge if you agree with everything.
[Part of openjournals/joss-reviews#7061]

Editing fixes for JOSS paper

---

paper/paper.md

- Add INRIA to remi's affiliation
- Reflect on Lune's name change

[JOSS] update affiliations

---

docs/source/changes.md
docs/source/index.rst
docs/source/workflow.md

DOCS add fmriprep version details
